name: noteit
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  percent_indicator: ^4.0.1
  gradients: ^0.1.1+2
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1



flutter:

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter.ttf

  uses-material-design: true

  assets:
    - assets/images/

